addons:
  apt:
    packages:
    - libgmp-dev
env: JRUBY_OPTS=--debug RAKE_TASK=spec
cache: bundler
language: ruby
matrix:
  include:
  - env: RAKE_TASK=rubocop
    rvm: '2.3.0'
rvm:
- '2.3.0'
- '2.2'
- '2.1'
script: bundle exec rake $RAKE_TASK
sudo: false
